APP:
  NAME: godev-kit
  VERSION: 1.0.0
  MODE: debug

HTTP:
  PORT: 8080
  USE_PREFORK_MODE: false

LOG:
  LEVEL: debug
  IN_COMMING_REQUEST:
    PRINT_REQUEST: true
    PRINT_RESPONSE: true
  OUT_COMMING_REQUEST:
    PRINT_REQUEST: true
    PRINT_RESPONSE: true
PG:
  POOL_MAX: 2
  URL: postgres://postgres:1@localhost:5433/godevkit

GRPC:
  PORT: 8081

RMQ:
  RPC_SERVER: rpc_server
  RPC_CLIENT: rpc_client
  URL: amqp://guest:guest@localhost:5672/

KAFKA:
  BROKERS:
    - localhost:9092
  GROUP_ID: godev-kit-group
  TOPICS:
    USER_EVENTS: dev.usere-vents
    # kafka-topics --create --topic dev.user-events --bootstrap-server localhost:9092 --replication-factor 1 --partitions 4
    TRANSLATION_EVENTS: dev.translation-events
    # kafka-topics --create --topic dev.translation-events --bootstrap-server localhost:9092 --replication-factor 1 --partitions 4

METRICS:
  ENABLED: true
  SKIP_PATHS: "/swagger/*;/metrics"
  PATH: "/metrics"
SWAGGER:
  ENABLED: true

JWT:
  SECRET: "123"