APP:
  NAME: godev-kit
  VERSION: 1.0.0

HTTP:
  PORT: 8080
  USE_PREFORK_MODE: false

LOG:
  LEVEL: debug

PG:
  POOL_MAX: 2
  URL: postgres://postgres:1@localhost:5433/godevkit

GRPC:
  PORT: 8081

RMQ:
  RPC_SERVER: rpc_server
  RPC_CLIENT: rpc_client
  URL: amqp://guest:guest@localhost:5672/

METRICS:
  ENABLED: false

SWAGGER:
  ENABLED: false